version: '3'

services:
  database:
    container_name: tradingbot-database
    image: postgres:14.1-alpine
    ports:
      - "5435:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:



